<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1718382528635' stop='1718382550067'>
    <name>Search Hotel</name>
    <title>Search Hotel</title>
    <test-cases>
        <test-case start='1718382528636' status='passed' stop='1718382544414'>
            <name>TC04: User can Search Hotel For Booking</name>
            <title>TC04: User can Search Hotel For Booking</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1718382544444' status='broken' stop='1718382550067'>
            <name>TC06: User can View Booked Hotel and Cancel the Order</name>
            <title>TC06: User can View Booked Hotel and Cancel the Order</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>The following error originated from your application code, not from Cypress.
                
                  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.
                
                The command that returned the promise was:
                
                  > `cy.click()`
                
                The cy command you invoked inside the promise was:
                
                  > `cy.log()`
                
                Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.
                
                Cypress will resolve your command with whatever the final Cypress command yields.
                
                The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.
                
                When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
                
                This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
                
                https://on.cypress.io/uncaught-exception-from-application
                
                https://on.cypress.io/returning-promise-and-commands-in-another-command</message>
                <stack-trace>CypressError: The following error originated from your application code, not from Cypress.
                
                  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.
                
                The command that returned the promise was:
                
                  > `cy.click()`
                
                The cy command you invoked inside the promise was:
                
                  > `cy.log()`
                
                Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.
                
                Cypress will resolve your command with whatever the final Cypress command yields.
                
                The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.
                
                When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
                
                This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
                
                https://on.cypress.io/uncaught-exception-from-application
                
                https://on.cypress.io/returning-promise-and-commands-in-another-command
                    at cy.&lt;computed> [as log] (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:138084:64)
                    at listener (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:140073:19)
                    at arrayMap (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:17765:23)
                    at map (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:26734:14)
                    at $Cy.emitMap (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:140075:14)
                    at parent.&lt;computed> [as emitMap] (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:140038:32)
                    at $Cypress.action (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:41157:21)
                    at onConfirm (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:138430:36)
                    at sendEvent (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:142724:32)
                    at sendMouseEvent (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:142075:12)
                    at sendClick (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:142136:12)
                    at Object._mouseClickEvents (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:142630:19)
                    at Object.click (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:142570:38)
                    at onReady (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:112194:37)
                    at onReady (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:112152:32)
                    at runAllChecks (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:112830:14)
                    at retryActionability (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:112852:16)
                    at tryCatcher (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:1807:23)
                    at Promise.attempt.Promise.try (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:4315:29)
                    at whenStable (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:143678:68)
                    at &lt;unknown> (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:143619:14)
                    at tryCatcher (https://adactinhotelapp.com/__cypress/runner/cypress_runner.js:1807:23)
                From Your Spec Code:
                    at Context.eval (webpack://hotelautomationcypress/./cypress/e2e/TestCases/SearchHotel.cy.js:64:16)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>