{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"Order ID does not exist in Cypress environment","children":[{"name":"TC06: User can View Booked Hotel and Cancel the Order","uid":"6fb447febbf33a48","parentUid":"bb3a5f99600b805128b3cddf307dbf73","status":"broken","time":{"start":1718382509214,"stop":1718382509888,"duration":674},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"bb3a5f99600b805128b3cddf307dbf73"},{"name":"The following error originated from your application code, not from Cypress.\n                \n                  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n                \n                The command that returned the promise was:\n                \n                  > `cy.click()`\n                \n                The cy command you invoked inside the promise was:\n                \n                  > `cy.log()`\n                \n                Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n                \n                Cypress will resolve your command with whatever the final Cypress command yields.\n                \n                The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n                \n                When Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n                \n                This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n                \n                https://on.cypress.io/uncaught-exception-from-application\n                \n                https://on.cypress.io/returning-promise-and-commands-in-another-command","children":[{"name":"TC06: User can View Booked Hotel and Cancel the Order","uid":"2898f7c10bed4339","parentUid":"b6f4ff51c69ae2d687c7f32b49a4d5a4","status":"broken","time":{"start":1718382544444,"stop":1718382550067,"duration":5623},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"b6f4ff51c69ae2d687c7f32b49a4d5a4"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}